Repository LIKECLOVA/LUCKIT, pull requests merged in 2022-12, with the labels that each got.

#19 Feat: 로그인 UI 구현
  src/components/join/join.jsx
  src/components/login/login.jsx
  src/components/login/loginstyle.jsx
Labels: ✨ Feature

#25 Feat: 프로필 수정 페이지 마크업 완료
  src/pages/pages.jsx
  src/pages/profile/editProfile.jsx
  src/pages/profile/editprofilestyle.jsx
  src/pages/profile/myprofilestyle.jsx
Labels: ✨ Feature

#32 Feat: 스플래쉬 UI 구현
  package-lock.json
  package.json
  src/assets/splash.png
  src/components/splash/splash.jsx
  src/components/splash/styled.jsx
  src/pages/pages.jsx
Labels: ✨ Feature

#37 Feat: 아이콘버튼 컴포넌트 작성
  src/assets/chat-disabled.png
  src/assets/chat.png
  src/assets/document-disabled.png
  src/assets/document.png
  src/assets/home-disabled.png
  src/assets/home-클로바.png
  src/assets/profile-disabled.png
  src/assets/profile.png
  src/assets/sns용-클로바-disabled.png
  src/assets/sns용-클로바.png
  src/components/button/iconBtn.jsx
  src/components/button/iconBtnstyle.jsx
  src/components/mainpost/mainpoststyle.jsx
  src/components/uploadbtn/uploadBtn.jsx
  src/components/uploadbtn/uploadstyle.jsx
  src/pages/sns/snsUpload.jsx
Labels: ✨ feature

#41 Feat/홈페이지 캐러셀 구현
  src/components/carousel/carousel.jsx
  src/components/carousel/carouselstyle.jsx
  src/pages/home/Home2.jsx
  src/pages/home/home.jsx
Labels: ✨ feature

#45 Fix: 캐러셀 컴포넌트 이미지 url 수정
  src/components/carousel/carousel.jsx
  src/components/carousel/carouselstyle.jsx
Labels: 🤔bug, 🌈 style

#47 Feat: 회원가입 프로필 설정 구현완료
  .eslintrc.json
  src/components/button/iconBtn.jsx
  src/components/join/joinProfile.jsx
  src/components/join/joinprofilestyle.jsx
Labels: ✨ feature

#48 Feat: 헤더 컴포넌트 구현
  src/components/button/button.jsx
  src/components/button/buttonstyle.jsx
  src/components/header/header.jsx
  src/components/header/headerstyle.jsx
  src/pages/chat/chatPage.jsx
  src/pages/chat/chatRoom.jsx
  src/pages/follow/myFollow.jsx
  src/pages/follow/yourFollow.jsx
  src/pages/home/Home2.jsx
  src/pages/home/home.jsx
  src/pages/profile/editProfile.jsx
  src/pages/profile/myProfile.jsx
  src/pages/profile/yourProfile.jsx
  src/pages/search/search.jsx
  src/pages/search/searchstyle.jsx
  src/pages/sns/snsPage.jsx
Labels: ✨ feature, 🌈 style

#53 Fix: 회원가입 프로필 설정 페이지 이미지 버튼 수정
  src/components/button/iconBtn.jsx
  src/components/button/iconBtnstyle.jsx
  src/components/join/joinProfile.jsx
  src/components/join/joinprofilestyle.jsx
Labels: 🤔bug

#56 Feat: myfollow 페이지 기능구현 완료
  src/components/button/iconBtn.jsx
  src/components/button/iconBtnstyle.jsx
  src/components/follow/follow.jsx
  src/components/follow/followstyle.jsx
  src/components/header/header.jsx
  src/components/header/headerstyle.jsx
  src/components/profile-box/profileBox.jsx
  src/components/profile-box/profilestyle.jsx
  src/pages/follow/myFollow.jsx
  src/pages/profile/myProfile.jsx
  src/pages/profile/myprofilestyle.jsx
Labels: ✨ feature

#57 Feat/마이 프로필 페이지 기능 구현
  src/components/market-preview-post/marketPreviewPost.jsx
  src/components/market-preview-post/marketpreviewboxstyle.jsx
  src/components/profile-box/profileBox.jsx
  src/components/profile-box/profilestyle.jsx
  src/pages/profile/myProfile.jsx
  src/pages/profile/myprofilestyle.jsx
Labels: ✨ feature

#66 Feat/프로필 페이지 기능 구현
  src/components/market-preview-post/marketPreviewPost.jsx
  src/components/market-preview-post/marketpreviewboxstyle.jsx
  src/components/navbar/navBar.jsx
  src/components/profile-box/profileBox.jsx
  src/components/profile-box/profilestyle.jsx
  src/pages/pages.jsx
  src/pages/profile/ProfileAndSnsPost.jsx
  src/pages/profile/myProfile.jsx
  src/pages/profile/myprofilestyle.jsx
  src/pages/profile/yourProfile.jsx
Labels: ✨ feature

#68 Fix/팔로우버튼기능수정
  src/components/market-preview-post/marketpreviewboxstyle.jsx
  src/components/navbar/navBar.jsx
  src/components/profile-box/profileBox.jsx
  src/components/profile-box/profilestyle.jsx
  src/pages/profile/myProfile.jsx
Labels: 🤔bug

#71 Feat/로그인
  .eslintrc.json
  package-lock.json
  package.json
  src/components/login/login.jsx
  src/components/login/loginstyle.jsx
  src/pages/pages.jsx
Labels: ✨ feature

#72 Fix: 로그인 버튼 수정
  src/components/login/loginstyle.jsx
Labels: 🤔bug

#78 Feat: 회원가입 기능 구현
  src/components/join/join.jsx
  src/components/join/joinProfile.jsx
  src/components/join/joinstyle.jsx
Labels: ✨ feature

#79 Feat: 프로필 수정 페이지 기능 완성
  package-lock.json
  package.json
  src/components/header/header.jsx
  src/components/join/joinProfile.jsx
  src/components/join/joinprofilestyle.jsx
  src/index.js
  src/pages/profile/editProfile.jsx
  src/pages/profile/editprofilestyle.jsx
  src/pages/sns/snsPage.jsx
  src/reducers/getUserInfoSlice.js
  src/store.js
Labels: ✨ feature

#80 Feat: 검색 페이지 기능 구현
  src/components/header/header.jsx
  src/components/header/headerstyle.jsx
  src/pages/profile/ProfilePost.jsx
  src/pages/profile/myProfile.jsx
  src/pages/profile/myprofilestyle.jsx
  src/pages/search/search.jsx
  src/pages/search/searchstyle.jsx
Labels: ✨ feature

#84 Feat: 회원가입 기능구현 완성
  .eslintrc.json
  src/components/button/button.jsx
  src/components/button/buttonstyle.jsx
  src/components/join/join.jsx
  src/components/join/joinProfile.jsx
  src/pages/search/searchstyle.jsx
Labels: ✨ feature

#87 Feat: 상대방 팔로우 페이지 기능구현 완료
  src/components/follow/follow.jsx
  src/components/follow/followstyle.jsx
  src/components/profile-box/profileBox.jsx
  src/pages/follow/followstyle.jsx
  src/pages/follow/myFollow.jsx
  src/pages/follow/yourFollow.jsx
  src/pages/profile/editProfile.jsx
  src/pages/profile/myProfile.jsx
Labels: ✨ feature

#93 [Feat] 마켓 업로드 UI 및 기능 구현
  src/components/button/button.jsx
  src/components/button/buttonstyle.jsx
  src/components/context/UserContext.jsx
  src/components/header/header.jsx
  src/components/join/joinstyle.jsx
  src/components/market-post/marketUpload/marketImage.jsx
  src/components/market-post/marketUpload/marketInput.jsx
  src/components/market-post/marketUpload/marketUpload.jsx
  src/components/market-post/marketUpload/marketinputstyle.jsx
  src/pages/pages.jsx
Labels: ✨ feature

#94 Feat: 로그인 인증에 따른 페이지 라우팅 기능 구현 완료
  src/Route.js
  src/pages/pages.jsx
  src/pages/start/start.jsx
Labels: ✨ feature

#95 Feat/모달창 기능 구현
  src/components/button/iconBtn.jsx
  src/components/header/header.jsx
  src/components/header/headerstyle.jsx
  src/components/mainpost/mainpoststyle.jsx
  src/components/market-preview-post/marketPreviewPost.jsx
  src/components/modal/modal.jsx
  src/components/modal/modalstyle.jsx
  src/pages/profile/ProfilePost.jsx
  src/pages/profile/myProfile.jsx
  src/pages/profile/myprofilestyle.jsx
  src/pages/sns/snsstyle.jsx
Labels: ✨ feature

#97 Feat: 프로필 수정 페이지에 저장 버튼 클릭시 페이지이동 기능 추가
  src/pages/profile/editProfile.jsx
Labels: ✨ feature, Refactoring

#99 Feat: 마켓 상품 수정 UI 및 기능 구현
  src/components/market-post/marketUpdate/marketUpdate.jsx
  src/pages/pages.jsx
Labels: ✨ feature

#101 Feat: 댓글 모달 기능 구현
  src/components/button/iconBtn.jsx
  src/components/comment/commentlist/commentList.jsx
  src/components/modal/modal.jsx
  src/components/modal/modalstyle.jsx
  src/components/navbar/navbarstyle.jsx
  src/pages/sns/snsPage.jsx
Labels: ✨ feature

#102 Fix: 상품 수정 주소 변경
  src/pages/pages.jsx
Labels: 📄docs

#107 Refactor: 프로필 페이지 sns 게시글 컴포넌트 수정
  src/pages/profile/myProfile.jsx
Labels: Refactoring

#113 Fix: sns게시글, 댓글 더보기 버튼 모달 기능 수정
  src/components/button/iconBtn.jsx
  src/components/comment/commentBox.jsx
  src/components/comment/commentlist/commentList.jsx
  src/components/mainpost/mainSnsPost.jsx
  src/components/modal/modal.jsx
  src/components/sns-post/snsPost.jsx
Labels: 🤔bug

#115 Refactor/홈페이지 마크업과 css 리팩토링
  package-lock.json
  package.json
  src/components/header/header.jsx
  src/components/modal/modal.jsx
  src/components/navbar/navBar.jsx
  src/pages/home/Home2.jsx
  src/pages/home/MarketFeedHome.jsx
  src/pages/home/defaultHome.jsx
  src/pages/home/home.jsx
  src/pages/home/homestyle.jsx
  src/pages/pages.jsx
Labels: ✨ feature, 🌈 style, Refactoring

#119 Design: 게시글 상세페이지 디자인
  src/components/mainpost/mainMarketPost.jsx
  src/components/mainpost/mainSnsPost.jsx
  src/components/mainpost/mainpoststyle.jsx
  src/components/sns-post/snsPost.jsx
  src/components/sns-post/snspoststyle.jsx
Labels: 🌈 style

#120 Feat: 댓글삭제 기능구현
  src/components/button/iconBtn.jsx
  src/components/comment/commentBox.jsx
  src/components/comment/commentlist/commentList.jsx
  src/components/modal/modal.jsx
Labels: ✨ feature

#122 Feat/홈페이지 axios 이용해 마켓 게시글 렌더링
  src/pages/home/MarketFeedHome.jsx
  src/pages/home/home.jsx
Labels: ✨ feature

#125 Feat: 마켓 상품 삭제 기능 구현
  src/components/market-post/marketUpdate/marketUpdate.jsx
  src/components/market-preview-post/marketPreviewPost.jsx
  src/components/modal/modal.jsx
Labels: ✨ feature

#127 Design: 홈 마켓 피드 모달 수정
  src/pages/home/MarketFeedHome.jsx
  src/styles/global/globalStyle.jsx
Labels: 🌈 style

#129 Feat: 홈 마켓 피드 디자인 수정
  src/assets/럭킷-홈-배너 복사.png
  src/assets/럭킷-홈-배너 복사2.png
  src/components/carousel/carousel.jsx
  src/components/carousel/carouselstyle.jsx
  src/pages/home/MarketFeedHome.jsx
  src/pages/home/homestyle.jsx
Labels: 🌈 style

#132 Design: Allwrap 디자인 수정
  src/App.js
  src/styles/global/Allwrap.jsx
Labels: 🌈 style

#133 Refactor/프로필페이지 css 등 리팩토링, 마켓 페이지 구현
  src/components/button/iconBtn.jsx
  src/components/button/iconBtnstyle.jsx
  src/components/mainpost/marketPostBox.jsx
  src/components/mainpost/marketpostboxstyle.jsx
  src/components/market-post/marketPreview.jsx
  src/components/market-preview-post/marketPreviewPost.jsx
  src/components/market-preview-post/marketpreviewboxstyle.jsx
  src/components/modal/modal.jsx
  src/components/navbar/navBar.jsx
  src/components/profile-box/profileBox.jsx
  src/components/profile-box/profilestyle.jsx
  src/pages/market/marketPost.jsx
  src/pages/market/marketpoststyle.jsx
  src/pages/pages.jsx
  src/pages/profile/myProfile.jsx
  src/pages/profile/myprofilestyle.jsx
Labels: ✨ feature, 🌈 style, 🛠 refactor

#131 Refactor: redux thunk로 데이터 불러오기
  src/components/button/button.jsx
  src/components/join/joinProfile.jsx
  src/components/market-preview-post/marketPreviewPost.jsx
  src/components/market-preview-post/marketpreviewboxstyle.jsx
  src/components/profile-box/profileBox.jsx
  src/pages/profile/editProfile.jsx
  src/pages/profile/myProfile.jsx
  src/pages/sns/snsPage.jsx
  src/reducers/getProductListSlice.js
  src/reducers/getUserInfoSlice.js
  src/store.js
Labels: 🛠 refactor

#135 Feat: 게시글업로드 오류해결
  src/pages/sns/snsUpload.jsx
Labels: 🤔 bug

#137 Feat: 게시글수정 기능구현
  src/components/button/iconBtn.jsx
  src/components/mainpost/mainSnsPost.jsx
  src/components/modal/modal.jsx
  src/pages/pages.jsx
  src/pages/sns/snsModify.jsx
Labels: ✨ feature

#138 Refactor: 홈페이지 마켓 게시글 컴포넌트 적용
  src/components/button/iconBtn.jsx
  src/components/mainpost/marketPostBox.jsx
  src/pages/home/MarketFeedHome.jsx
  src/pages/home/homestyle.jsx
Labels: 🛠 refactor

#139 Fix: 상품 수정 기능 구현 수정
  package-lock.json
  package.json
  src/components/market-post/marketUpdate/marketUpdate.jsx
  src/pages/market/marketPost.jsx
  src/styles/global/Allwrap.jsx
Labels: 🤔 bug

#141 Refactor/검색페이지와마켓게시글코드수정
  src/components/mainpost/marketPostBox.jsx
  src/components/market-preview-post/marketPreviewPost.jsx
  src/pages/home/MarketFeedHome.jsx
  src/pages/market/marketPost.jsx
  src/pages/profile/myProfile.jsx
  src/pages/search/search.jsx
  src/pages/search/searchstyle.jsx
Labels: 🛠 refactor

#143 Design/css수정
  src/components/carousel/carousel.jsx
  src/components/carousel/carouselstyle.jsx
  src/components/login/loginstyle.jsx
  src/components/navbar/navBar.jsx
  src/pages/home/homestyle.jsx
  src/pages/profile/myProfile.jsx
  src/styles/global/Allwrap.jsx
Labels: 🌈 style

#144 Fix: 캐러셀 이미지 수정
  src/components/carousel/carousel.jsx
  src/pages/pages.jsx
Labels: 🌈 style

#149 Feat/홈과프로필페이지게시글등록버튼구현
  src/components/button/iconBtn.jsx
  src/components/button/iconBtnstyle.jsx
  src/components/market-preview-post/marketPreviewPost.jsx
  src/components/market-preview-post/marketpreviewboxstyle.jsx
  src/pages/home/MarketFeedHome.jsx
  src/pages/home/defaultHome.jsx
  src/pages/profile/myProfile.jsx
  src/pages/profile/myprofilestyle.jsx
  src/pages/sns/snsPage.jsx
  src/pages/sns/snsstyle.jsx
Labels: ✨ feature

#152 Fix: 홈페이지 onScroll 이벤트 재렌더링 관련 코드 수정
  src/pages/home/MarketFeedHome.jsx
  src/pages/home/home.jsx
Labels: 🤔 bug

#154 Fix: 프로필 페이지 정보 불러오기 오류 수정
  src/components/market-preview-post/marketPreviewPost.jsx
  src/components/profile-box/profileBox.jsx
Labels: 🤔 bug

#155 Feat: 뒤로가기 버튼 컴포넌트 구현
  src/components/button/iconBtn.jsx
  src/components/button/iconBtnstyle.jsx
  src/components/header/header.jsx
Labels: ✨ feature

#157 Refactor/헤더뒤로가기컴포넌트적용과정리
  src/components/header/header.jsx
  src/components/header/headerstyle.jsx
  src/pages/follow/myFollow.jsx
  src/pages/follow/yourFollow.jsx
Labels: 🛠 refactor

#159 Fix: 상대방 팔로우 팔로워 페이지에서 내 프로필을 팔로우 하는 버튼이 보이는 오류 해결
  src/components/follow/follow.jsx
  src/components/follow/followstyle.jsx
  src/pages/follow/myFollow.jsx
  src/pages/follow/yourFollow.jsx
  src/reducers/getFollowSlice.js
  src/store.js
Labels: 😆 fix

#162 Feat: 카카오맵 api 지도 기능 구현 완료
  .env
  package-lock.json
  package.json
  public/index.html
  src/assets/icon/mapMarker.png
  src/assets/icon/맛집.jpeg
  src/assets/icon/몰랑.gif
  src/assets/icon/산책.webp
  src/assets/icon/집꾸미기.webp
  src/pages/home/MarketFeedHome.jsx
  src/pages/map/ eventMarker.js
  src/pages/map/map.jsx
  src/pages/map/mapModal.jsx
  src/pages/map/markPosition.jsx
  src/pages/map/stylemap.jsx
  src/pages/market/marketPost.jsx
  src/pages/pages.jsx
Labels: ✨ feature

#163 Design/프로필페이지css수정
  src/components/button/iconBtn.jsx
  src/components/button/iconBtnstyle.jsx
  src/components/mainpost/marketPostBox.jsx
  src/components/mainpost/marketpostboxstyle.jsx
  src/components/market-preview-post/marketPreviewPost.jsx
  src/components/market-preview-post/marketpreviewboxstyle.jsx
  src/components/market-preview-post/marketpreviewpoststyle.jsx
  src/components/profile-box/profileBox.jsx
  src/components/profile-box/profileboxstyle.jsx
  src/components/profile-box/profilestyle.jsx
  src/pages/market/marketPost.jsx
  src/pages/market/marketpoststyle.jsx
  src/pages/profile/ProfilePost.jsx
  src/pages/profile/myProfile.jsx
  src/pages/profile/myprofilestyle.jsx
  src/styles/global/Allwrap.jsx
Labels: 🌈 style

#164 Feat/게시글활성화버튼
  src/components/button/button.jsx
  src/components/button/buttonstyle.jsx
  src/components/button/iconBtnstyle.jsx
  src/components/header/header.jsx
  src/components/header/headerstyle.jsx
  src/pages/chat/chatPage.jsx
  src/pages/chat/chatRoom.jsx
  src/pages/chat/chatUser.jsx
  src/pages/chat/chatpagestyle.jsx
  src/pages/chat/chatuserstyle.jsx
  src/pages/sns/snsUpload.jsx
  src/styles/global/Allwrap.jsx
Labels: ✨ feature, 🌈 style

#165 Fix: 로그인, 회원가입, 스플래쉬, 로그인 스크린 CSS 수정
  src/assets/loginScreen-logo.png
  src/components/join/joinstyle.jsx
  src/components/login/loginScreen.jsx
  src/components/login/loginstyle.jsx
  src/components/login/logscreenstyle.jsx
  src/components/splash/styled.jsx
  src/styles/global/Allwrap.jsx
Labels: 🌈 style, 😆 fix

#169 Design/검색과홈페이지css수정
  src/components/carousel/carousel.jsx
  src/components/carousel/carouselstyle.jsx
  src/pages/home/MarketFeedHome.jsx
  src/pages/home/defaultHome.jsx
  src/pages/home/home.jsx
  src/pages/home/homestyle.jsx
  src/pages/market/marketpoststyle.jsx
  src/pages/profile/myProfile.jsx
  src/pages/profile/myprofilestyle.jsx
  src/pages/search/search.jsx
  src/pages/search/searchstyle.jsx
Labels: 🌈 style

#171 Design/모달과네비바css수정
  src/components/header/header.jsx
  src/components/header/headerstyle.jsx
  src/components/modal/modal.jsx
  src/components/modal/modalstyle.jsx
  src/components/navbar/navbarstyle.jsx
  src/pages/home/homestyle.jsx
Labels: 🌈 style

#170 Style: 채팅 페이지 css 작업 완료
  src/assets/icon/달무티.jpeg
  src/assets/icon/몰랑이.png
  src/assets/icon/쿠로미.png
  src/components/header/header.jsx
  src/pages/chat/chatPage.jsx
  src/pages/chat/chatRoom.jsx
  src/pages/chat/chatUser.jsx
  src/pages/chat/chatpagestyle.jsx
  src/pages/chat/chatroomstyle.jsx
  src/pages/chat/chatuserstyle.jsx
Labels: 🌈 style

#172 Fix: 에러 이미지 처리
  .gitignore
  src/components/mainpost/marketPostBox.jsx
  src/components/market-preview-post/marketPreviewPost.jsx
Labels: 😆 fix

#173 Feat: 채팅 페이지 & 지도 페이지 네브바 추가
  src/components/navbar/navbarstyle.jsx
  src/pages/chat/chatPage.jsx
  src/pages/map/map.jsx
Labels: ✨ feature

#174 Design: 에러 페이지 디자인
  src/assets/notFound.png
  src/components/mainpost/marketPostBox.jsx
  src/pages/404-error/errorPage.jsx
  src/styles/global/globalStyle.jsx
Labels: 🌈 style

#175 Design:sns피드페이지 디자인
  src/components/mainpost/mainpoststyle.jsx
  src/pages/profile/myprofilestyle.jsx
Labels: 🌈 style

#177 Design: Navbar 아이콘 변경 및 에러페이지 Navbar 추가
  src/assets/icon/locator-disabled.png
  src/assets/icon/locator.png
  src/components/navbar/navBar.jsx
  src/components/navbar/navbarstyle.jsx
  src/pages/404-error/errorPage.jsx
Labels: 🌈 style, 😆 fix

#178 Style: 팔로우 페이지 css 수정 완료
  src/components/follow/follow.jsx
  src/components/follow/followstyle.jsx
  src/pages/follow/followstyle.jsx
Labels: 🌈 style

#179 Design: 헤더 CSS 수정
  src/components/header/header.jsx
  src/components/header/headerstyle.jsx
Labels: 🌈 style

#181 Style: 프로필 수정 페이지 css 수정 완료
  src/pages/profile/editProfile.jsx
  src/pages/profile/editprofilestyle.jsx
Labels: 🌈 style

#183 Fix: profile 수정 바로 안되는 문제 해결
  src/components/profile-box/profileBox.jsx
Labels: 😆 fix

#185 Style: 회원가입 프로필 설정 페이지 css 수정
  src/components/button/buttonstyle.jsx
  src/components/button/iconBtnstyle.jsx
  src/components/join/joinProfile.jsx
  src/components/join/joinprofilestyle.jsx
Labels: 🌈 style

#188 Feat: 게시물수정버튼 활성화 기능구현
  src/pages/sns/snsModify.jsx
Labels: ✨ feature

#191 Design: sns피드페이지 디자인
  src/components/button/iconBtn.jsx
  src/components/button/iconBtnstyle.jsx
  src/components/mainpost/mainpoststyle.jsx
  src/pages/sns/snsstyle.jsx
Labels: 🌈 style

#193 Design: sns업로드페이지 디자인
  src/pages/sns/snsstyle.jsx
Labels: 🌈 style

#194 Feat: sns상세페이지 디자인
  src/components/button/iconBtn.jsx
  src/components/button/iconBtnstyle.jsx
  src/components/comment/commentboxstyle.jsx
  src/components/comment/commentinput/commentinputstyle.jsx
  src/components/comment/commentlist/commentList.jsx
  src/components/comment/commentlist/commentliststyle.jsx
  src/components/mainpost/mainpoststyle.jsx
  src/components/sns-post-box/snsPostBox.jsx
  src/components/sns-post/snsPost.jsx
  src/components/sns-post/snspoststyle.jsx
Labels: 🌈 style

#196 Rename: 상세페이지 게시글삭제 시 프로필로 이동
  src/components/modal/modal.jsx
Labels: 😆 fix
