Repository LIKECLOVA/LUCKIT, pull requests merged in 2023-01, with the labels that each got.

#198 refactor: sns페이지 리팩토링
  src/components/button/button.jsx
  src/components/button/buttonstyle.jsx
  src/components/comment/commentinput/commentInput.jsx
  src/components/comment/commentlist/commentList.jsx
  src/components/mainpost/mainSnsPost.jsx
  src/components/sns-post/snsPost.jsx
  src/pages/sns/snsModify.jsx
  src/pages/sns/snsPage.jsx
  src/pages/sns/snsUpload.jsx
  src/pages/sns/snsstyle.jsx
Labels: 🛠 refactor

#201 Design: 맵 마커 아이콘 변경 및 모달 CSS 수정
  src/assets/icon/marker-클로바-임시 복사.png
  src/components/login/loginstyle.jsx
  src/pages/map/eventMarker.jsx
  src/pages/map/mapModal.jsx
  src/pages/map/stylemap.jsx
  src/pages/market/marketpoststyle.jsx
Labels: 🌈 style, 😆 fix

#202 Fix/sns페이지axios변경
  src/pages/sns/snsPage.jsx
Labels: 🛠 refactor, 😆 fix

#204 Refactor: 변수명 등 코드 수정
  src/components/button/iconBtn.jsx
  src/components/comment/commentlist/commentList.jsx
  src/components/mainpost/mainSnsPost.jsx
  src/components/market-preview-post/marketPreviewPost.jsx
  src/components/modal/modal.jsx
  src/components/navbar/navBar.jsx
  src/components/profile-box/profileBox.jsx
  src/pages/home/MarketFeedHome.jsx
  src/pages/home/defaultHome.jsx
  src/pages/home/home.jsx
  src/pages/home/homestyle.jsx
  src/pages/market/marketPost.jsx
  src/pages/profile/myProfile.jsx
  src/pages/profile/myprofilestyle.jsx
  src/pages/search/search.jsx
  src/pages/sns/snsModify.jsx
  src/pages/sns/snsPage.jsx
  src/pages/sns/snsUpload.jsx
Labels: 🛠 refactor

#205 Design: 홈 피드 모달 사진 및 CSS 수정
  src/components/mainpost/marketPostBox.jsx
Labels: 🌈 style, 😆 fix

#207 Design: SNS 피드 CSS 수정
  src/assets/icon/icon-heart.svg
  src/assets/icon/icon-message-circle.svg
  src/components/button/heart/heartBtn.jsx
  src/components/button/heart/heartbtnstyle.jsx
  src/components/comment/commentlist/commentliststyle.jsx
  src/components/mainpost/mainSnsPost.jsx
  src/components/mainpost/mainpoststyle.jsx
  src/components/market-preview-post/marketpreviewpoststyle.jsx
Labels: 🌈 style

#208 Refactor: 프로필 페이지 sns 게시글 없어도 snsPostBtn 뜨도록 수정
  src/components/mainpost/marketpostboxstyle.jsx
  src/pages/profile/myProfile.jsx
Labels: 🛠 refactor

#209 Fix: sns페이지 리팩토링
  src/components/mainpost/mainSnsPost.jsx
  src/components/mainpost/mainpoststyle.jsx
Labels: 🛠 refactor, 😆 fix

#212 Refactor: sns 페이지 axios 리덕스로 수정
  src/pages/home/MarketFeedHome.jsx
  src/pages/home/home.jsx
  src/pages/sns/snsPage.jsx
Labels: 🛠 refactor

#213 Design: SNS 피드 디자인 수정
  src/assets/icon/icon- more-vertical.png
  src/assets/icon/icon-arrow-left.png
  src/assets/icon/icon-post-album-off.png
  src/assets/icon/icon-post-album-on.png
  src/assets/icon/icon-post-list-off.png
  src/assets/icon/icon-post-list-on.png
  src/assets/icon/s-icon-more-vertical.png
  src/components/button/iconBtnstyle.jsx
  src/components/comment/commentlist/commentliststyle.jsx
  src/components/header/headerstyle.jsx
  src/components/mainpost/mainSnsPost.jsx
  src/components/mainpost/mainpoststyle.jsx
  src/components/market-preview-post/marketpreviewpoststyle.jsx
  src/components/sns-post/snspoststyle.jsx
Labels: 🌈 style

#215 Design: SNS 피드 디자인 수정
  src/assets/icon/icon-search.png
  src/assets/icon/x.svg
  src/components/button/iconBtn.jsx
  src/components/button/iconBtnstyle.jsx
  src/components/comment/commentlist/commentliststyle.jsx
  src/components/join/joinprofilestyle.jsx
  src/components/profile-box/profileBox.jsx
  src/components/profile-box/profileboxstyle.jsx
  src/components/sns-post/snspoststyle.jsx
  src/pages/chat/chatuserstyle.jsx
  src/pages/profile/editprofilestyle.jsx
  src/pages/search/searchstyle.jsx
Labels: 🌈 style

#216 Feat: sns피드 무한스크롤 기능구현
  package-lock.json
  package.json
  src/components/loading/loading.jsx
  src/pages/sns/snsPage.jsx
Labels: ✨ feature

#218 fix: sns피드비율조정
  src/components/comment/commentlist/commentliststyle.jsx
  src/components/mainpost/mainpoststyle.jsx
  src/pages/sns/snsPage.jsx
Labels: 😆 fix

#219 Design: SNS 피드 댓글, 헤더 디자인 수정
  src/assets/icon/addBtn.png
  src/components/button/iconBtnstyle.jsx
  src/components/comment/commentinput/commentinputstyle.jsx
  src/components/header/header.jsx
  src/components/header/headerstyle.jsx
  src/components/mainpost/mainpoststyle.jsx
  src/components/profile-box/profileboxstyle.jsx
  src/pages/sns/snsPage.jsx
  src/pages/sns/snsstyle.jsx
Labels: 🌈 style, 😆 fix

#221 Feat/앨범형게시글이미지링크연결등구현
  src/components/button/button.jsx
  src/components/button/buttonstyle.jsx
  src/pages/profile/myProfile.jsx
  src/pages/profile/myprofilestyle.jsx
Labels: ✨ feature, 🛠 refactor

#222 Fix: sns페이지 css수정
  src/components/button/heart/heartbtnstyle.jsx
  src/components/button/iconBtnstyle.jsx
  src/components/mainpost/mainpoststyle.jsx
  src/components/sns-post/snspoststyle.jsx
  src/pages/sns/snsstyle.jsx
  src/styles/global/globalColor.jsx
Labels: 😆 fix

#223 Design/채팅
  src/assets/icon/addBtn2.png
  src/assets/icon/uploadBtn.png
  src/components/header/headerstyle.jsx
  src/pages/chat/chatPage.jsx
  src/pages/chat/chatRoom.jsx
  src/pages/chat/chatUser.jsx
  src/pages/chat/chatpagestyle.jsx
  src/pages/chat/chatroomstyle.jsx
  src/pages/chat/chatuserstyle.jsx
Labels: 🌈 style

#224 Refactor: 전체적인 CSS 코드 수정
  src/components/header/headerstyle.jsx
  src/components/mainpost/marketpostboxstyle.jsx
  src/components/market-preview-post/marketPreviewPost.jsx
  src/components/market-preview-post/marketpreviewpoststyle.jsx
  src/components/navbar/navbarstyle.jsx
  src/components/profile-box/profileboxstyle.jsx
  src/pages/home/homestyle.jsx
  src/pages/market/marketPost.jsx
  src/pages/market/marketpoststyle.jsx
  src/pages/profile/myprofilestyle.jsx
  src/pages/search/searchstyle.jsx
Labels: 🌈 style

#225 Design: 전반적인 CSS 디테일 수정
  src/assets/splash.png
  src/components/button/button.jsx
  src/components/button/buttonstyle.jsx
  src/components/button/heart/heartbtnstyle.jsx
  src/components/button/iconBtnstyle.jsx
  src/components/context/UserContext.jsx
  src/components/header/header.jsx
  src/components/header/headerstyle.jsx
  src/components/join/joinstyle.jsx
  src/components/login/loginstyle.jsx
  src/components/login/logscreenstyle.jsx
  src/components/mainpost/mainpoststyle.jsx
  src/components/mainpost/marketPostBox.jsx
  src/components/market-post/marketUpload/marketUpload.jsx
  src/components/market-post/marketUpload/marketinputstyle.jsx
  src/components/market-preview-post/marketPreviewPost.jsx
  src/components/market-preview-post/marketpreviewpoststyle.jsx
  src/components/navbar/navbarstyle.jsx
  src/components/profile-box/profileboxstyle.jsx
  src/components/splash/styled.jsx
  src/pages/chat/chatuserstyle.jsx
Labels: 🌈 style

#226 Rename: 파일명 및 컨벤션 정리
  src/App.js
  src/assets/icon/mapMarker.png
  src/components/button/heartBtn/heartBtn.jsx
  src/components/button/heartBtn/heartbtnstyle.jsx
  src/components/button/iconBtn.jsx
  src/components/button/iconbtnstyle.jsx
  src/components/footer/footer.jsx
  src/components/mainpost/mainSnsPost.jsx
  src/components/mainpost/mainsnspoststyle.jsx
  src/components/market-preview-post/marketpreviewpoststyle.jsx
  src/components/modal/snsModal.jsx
  src/components/search/search.jsx
  src/components/splash/styled.jsx
  src/pages/chat/chatroomstyle.jsx
  src/pages/home/home.jsx
  src/pages/map/mapModal.jsx
  src/pages/map/mapstyle.jsx
  src/pages/map/markPosition.jsx
  src/styles/global/allWrap.jsx
Labels: 📄 docs

#228 Design: 회원가입 프로필 설정 페이지 CSS 수정
  src/components/button/button.jsx
  src/components/button/buttonstyle.jsx
  src/components/button/iconbtnstyle.jsx
  src/components/join/joinProfile.jsx
  src/components/join/joinprofilestyle.jsx
Labels: 🌈 style

#229 Feat: 모든 페이지 헬멧 추가
  package-lock.json
  package.json
  src/components/sns-post/snsPost.jsx
  src/pages/404-error/errorPage.jsx
  src/pages/chat/chatPage.jsx
  src/pages/chat/chatRoom.jsx
  src/pages/follow/myFollow.jsx
  src/pages/follow/yourFollow.jsx
  src/pages/home/defaultHome.jsx
  src/pages/home/home.jsx
  src/pages/map/map.jsx
  src/pages/market/marketPost.jsx
  src/pages/profile/editProfile.jsx
  src/pages/profile/myProfile.jsx
  src/pages/search/search.jsx
  src/pages/sns/snsModify.jsx
  src/pages/sns/snsPage.jsx
  src/pages/sns/snsUpload.jsx
Labels: ✨ feature, 🛠 refactor

#230 Design: 쿠로미 채팅방 연결
  src/components/header/header.jsx
  src/pages/chat/chatPage.jsx
  src/pages/chat/chatRoom.jsx
  src/pages/chat/chatRoomSec.jsx
  src/pages/pages.jsx
Labels: 🌈 style

#231 Fix: key 값 id로 수정
  src/pages/map/map.jsx
  src/pages/sns/snsPage.jsx
Labels: 🛠 refactor

#232 Fix: SNS 피드 게시글 잘림 해결
  src/components/navbar/navBar.jsx
  src/pages/map/map.jsx
  src/pages/sns/snsPage.jsx
  src/pages/sns/snsstyle.jsx
Labels: 🌈 style, 😆 fix

#233 Docs: SNS 철자 수정
  src/pages/sns/snsModify.jsx
  src/pages/sns/snsPage.jsx
  src/pages/sns/snsUpload.jsx
Labels: 📄 docs

#235 Design: 채팅 페이지 CSS 수정
  src/pages/chat/chatuserstyle.jsx
  src/pages/home/homestyle.jsx
Labels: 🌈 style, 😆 fix

#236 Refactor: 회원가입 프로필 설정페이지 유효성 검사 문구 수정
  src/components/join/joinProfile.jsx
Labels: 🛠 refactor

#237 Fix/sns페이지css정리
  src/components/comment/commentlist/commentliststyle.jsx
  src/components/mainpost/mainsnspoststyle.jsx
  src/components/sns-post/snspoststyle.jsx
  src/pages/sns/snsPage.jsx
  src/pages/sns/snsstyle.jsx
Labels: 🌈 style, 🛠 refactor

#238 Fix/글자깨짐현상해결
  src/components/follow/followstyle.jsx
  src/pages/follow/followstyle.jsx
  src/pages/sns/snsstyle.jsx
Labels: 🌈 style, 😆 fix

#239 Design: sns 페이지 CSS 수정
  src/pages/sns/snsstyle.jsx
Labels: 🌈 style

#242 Fix: 마커 위치조정
  src/pages/map/markPosition.jsx
Labels: 🛠 refactor

#243 Fix: 팔로우 컴포넌트 아이디 닉네임 위치변경
  src/components/follow/follow.jsx
Labels: 🛠 refactor

#244 Fix: Helmet 중복되는부분 삭제
  src/App.js
  src/components/sns-post/snsPost.jsx
  src/pages/404-error/errorPage.jsx
  src/pages/chat/chatPage.jsx
  src/pages/chat/chatRoom.jsx
  src/pages/chat/chatRoomSec.jsx
  src/pages/follow/myFollow.jsx
  src/pages/follow/yourFollow.jsx
  src/pages/home/defaultHome.jsx
  src/pages/home/home.jsx
  src/pages/map/map.jsx
  src/pages/market/marketPost.jsx
  src/pages/profile/editProfile.jsx
  src/pages/profile/myProfile.jsx
  src/pages/search/search.jsx
  src/pages/sns/snsModify.jsx
  src/pages/sns/snsPage.jsx
  src/pages/sns/snsUpload.jsx
Labels: 🛠 refactor

#246 Docs: 리드미 수정 및 develop 브랜치와 싱크 맞추기
  README.md
  public/index.html
  src/components/login/loginstyle.jsx
  src/components/login/logscreenstyle.jsx
  src/pages/pages.jsx
Labels: 📄 docs

#247 [Feat] loading 페이지 구현
  src/assets/asset.md
  src/assets/spinner/spinner.gif
  src/components/loading/loading.jsx
  src/components/loading/loadingstyle.jsx
  src/pages/home/MarketFeedHome.jsx
  src/pages/home/home.jsx
  src/pages/sns/snsPage.jsx
Labels: ✨ feature

#248 Feat: 로딩페이지 기능 추가
  src/assets/asset.md
  src/assets/spinner/spinner.gif
  src/components/loading/loading.jsx
  src/components/loading/loadingstyle.jsx
  src/pages/home/MarketFeedHome.jsx
  src/pages/home/home.jsx
  src/pages/sns/snsPage.jsx
Labels: ✨ feature
